<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Moon</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Bind.fs" />
        <Compile Include="MetaDict.fs" />
        <Compile Include="Res.fs" />
        <Compile Include="Compo.fs" />
        <Compile Include="Injector.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\library\Moon.Extend\Moon.Extend.fsproj" />
    </ItemGroup>

</Project>
