<Project Sdk="Godot.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">$(AndroidFrameworkVersion)</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <RootNamespace>Moon</RootNamespace>
        <EnableGodotWarningGenerator>true</EnableGodotWarningGenerator>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\Moon.Injection.Class\Moon.Injection.Class.csproj" />
    </ItemGroup>
</Project>
