<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Moon</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="PhysicsQuery.fs" />
        <Compile Include="PhysicsQueryResult.fs" />
        <Compile Include="PhysicsState.fs" />
        <Compile Include="PhysicsQueryPoint.fs" />
        <Compile Include="PhysicsQueryRaycast.fs" />
        <Compile Include="PhysicsQueryShape.fs" />
        <Compile Include="PhysicsScope.fs" />
        <Compile Include="PhysicsCollide.fs" />
        <Compile Include="PhysicsMotion.fs" />
        <Compile Include="PhysicsServer2D.fs" />
        <Compile Include="PhysicsServer3D.fs" />
        <Compile Include="CSharp.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\library\Moon.Module\Moon.Module.fsproj" />
      <ProjectReference Include="..\..\library\Moon.CSharp\Moon.CSharp.csproj" />
      <ProjectReference Include="..\..\library\Moon.Utils\Moon.Utils.fsproj" />
      <ProjectReference Include="..\..\library\Moon.Game\Moon.Game.fsproj" />
      <ProjectReference Include="..\Moon.Injection\Moon.Injection.fsproj" />
      <ProjectReference Include="..\Moon.Physics.Class\Moon.Physics.Class.csproj" />
    </ItemGroup>

</Project>
